### ISSUE TITLE
ExceptionInInitializerError when Compiling WADs

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#12]
Version: 0.0.0
Stacktrace: java.lang.ExceptionInInitializerError
    at org.abimon.mods.danganronpa.launcher.DanganLauncher$3.run(DanganLauncher.java:691)
Caused by: java.lang.NullPointerException
    at org.abimon.mods.danganronpa.launcher.DanganModding.reload(DanganModding.java:254)
    at org.abimon.mods.danganronpa.launcher.DanganModding.<clinit>(DanganModding.java:61)
    ... 1 more

More Info: OS: MACOSX
This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.ExceptionInInitializerError
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$3.run(DanganLauncher.java:691)
Caused by: java.lang.NullPointerException
	at org.abimon.mods.danganronpa.launcher.DanganModding.reload(DanganModding.java:254)
	at org.abimon.mods.danganronpa.launcher.DanganModding.<clinit>(DanganModding.java:61)
	... 1 more

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL
