### ISSUE TITLE
RuntimeException when Running SPIRAL

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#2]
Version: 0.1.0
Stacktrace: java.lang.RuntimeException: This is just a test!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.main(DanganLauncher.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.RuntimeException: This is just a test!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.main(DanganLauncher.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.RuntimeException: This is just a test!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.main(DanganLauncher.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

This comment was autogenerated by SPIRAL
