### ISSUE TITLE
IOException when Backing up WAD File

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#3]
Version: 0.0.0
Stacktrace: java.io.IOException: Testing!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$1$1.run(DanganLauncher.java:393)

More Info: OS: MACOSX, WAD File: /Users/undermybrella/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/resources/dr2_data.wad
This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: Testing!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$1$1.run(DanganLauncher.java:393)

More Info: OS: MACOSX, WAD File: /Users/undermybrella/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/resources/dr2_data.wad
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: Testing!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$1$1.run(DanganLauncher.java:396)

More Info: OS: MACOSX, WAD File: /Users/undermybrella/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/resources/dr2_data.wad
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: Testing!
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$1$1.run(DanganLauncher.java:396)

More Info: OS: MACOSX, WAD File: /Users/*************/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/resources/dr2_data.wad
This comment was autogenerated by SPIRAL
