### ISSUE TITLE
IOException when Compiling WADs

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#5]
Version: 0.0.0
Stacktrace: java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1012)
    at org.abimon.omnis.io.Data.write(Data.java:196)
    at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:641)

More Info: OS: MACOSX
This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.abimon.omnis.io.Data.write(Data.java:196)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:641)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.abimon.omnis.io.Data.write(Data.java:196)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:647)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.abimon.omnis.io.Data.write(Data.java:196)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:652)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.abimon.omnis.io.Data.write(Data.java:196)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:652)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL
