### ISSUE TITLE
NullPointerException when Compiling WADs

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#6]
Version: 0.0.0
Stacktrace: java.lang.NullPointerException
    at org.abimon.omnis.util.General.iterateDirs(General.java:100)
    at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:662)

More Info: OS: MACOSX
This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.NullPointerException
	at org.abimon.omnis.util.General.iterateDirs(General.java:100)
	at org.abimon.omnis.util.General.iterateDirs(General.java:102)
	at org.abimon.omnis.util.General.iterateDirs(General.java:102)
	at org.abimon.omnis.util.General.iterateDirs(General.java:102)
	at org.abimon.omnis.util.General.iterateDirs(General.java:102)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$3$1.run(DanganLauncher.java:669)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL
