### ISSUE TITLE
FileNotFoundException when Restoring from Language Backup

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#8]
Version: 0.0.0
Stacktrace: java.io.FileNotFoundException: /Users/undermybrella/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/Resources/dr2_data_us.wad.backup (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at org.abimon.mods.danganronpa.launcher.DanganLauncher$2$1.run(DanganLauncher.java:534)

More Info: OS: MACOSX, WAD File: /Users/*************/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/Resources/dr2_data_us.wad
This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.io.FileNotFoundException: /Users/undermybrella/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/Resources/dr2_data_us.wad.backup (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher$2$1.run(DanganLauncher.java:534)

More Info: OS: MACOSX, WAD File: /Users/*************/Library/Application Support/Steam/steamapps/common/Danganronpa 2 Goodbye Despair/Danganronpa2.app/Contents/Resources/dr2_data_us.wad
This comment was autogenerated by SPIRAL
