### ISSUE TITLE
IndexOutOfBoundsException when Running DanganLauncher

### ISSUE THREAD

**Issue by UnderMybrella** [UnderMybrella/Spiral#9]
Version: 0.0.0
Stacktrace: java.lang.IndexOutOfBoundsException: The row index 19 must be less than or equal to 17.
	at com.jgoodies.forms.layout.CellConstraints.ensureValidGridBounds(CellConstraints.java:967)
	at com.jgoodies.forms.layout.FormLayout.setConstraints(FormLayout.java:822)
	at com.jgoodies.forms.layout.FormLayout.addLayoutComponent(FormLayout.java:1180)
	at java.awt.Container.addImpl(Container.java:1127)
	at java.awt.Container.add(Container.java:973)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.initialize(DanganLauncher.java:1103)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.<init>(DanganLauncher.java:286)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.lambda$main$0(DanganLauncher.java:272)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

More Info: OS: MACOSX
This issue was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.IndexOutOfBoundsException: The row index 19 must be less than or equal to 17.
	at com.jgoodies.forms.layout.CellConstraints.ensureValidGridBounds(CellConstraints.java:967)
	at com.jgoodies.forms.layout.FormLayout.setConstraints(FormLayout.java:822)
	at com.jgoodies.forms.layout.FormLayout.addLayoutComponent(FormLayout.java:1180)
	at java.awt.Container.addImpl(Container.java:1127)
	at java.awt.Container.add(Container.java:973)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.initialize(DanganLauncher.java:1103)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.<init>(DanganLauncher.java:286)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.lambda$main$0(DanganLauncher.java:272)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.IndexOutOfBoundsException: The row index 19 must be less than or equal to 17.
	at com.jgoodies.forms.layout.CellConstraints.ensureValidGridBounds(CellConstraints.java:967)
	at com.jgoodies.forms.layout.FormLayout.setConstraints(FormLayout.java:822)
	at com.jgoodies.forms.layout.FormLayout.addLayoutComponent(FormLayout.java:1180)
	at java.awt.Container.addImpl(Container.java:1127)
	at java.awt.Container.add(Container.java:973)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.initialize(DanganLauncher.java:1103)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.<init>(DanganLauncher.java:286)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.lambda$main$0(DanganLauncher.java:272)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL

**Comment by UnderMybrella** [comment]
Reproduced on version 0.0.0 with stacktrace
java.lang.IndexOutOfBoundsException: The row index 19 must be less than or equal to 17.
	at com.jgoodies.forms.layout.CellConstraints.ensureValidGridBounds(CellConstraints.java:967)
	at com.jgoodies.forms.layout.FormLayout.setConstraints(FormLayout.java:822)
	at com.jgoodies.forms.layout.FormLayout.addLayoutComponent(FormLayout.java:1180)
	at java.awt.Container.addImpl(Container.java:1127)
	at java.awt.Container.add(Container.java:973)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.initialize(DanganLauncher.java:1103)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.<init>(DanganLauncher.java:286)
	at org.abimon.mods.danganronpa.launcher.DanganLauncher.lambda$main$0(DanganLauncher.java:272)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

More Info: OS: MACOSX
This comment was autogenerated by SPIRAL
